import {
  LayoutDashboard,
  Users,
  GraduationCap,
  CalendarCheck,
  Wallet,
  Briefcase,
  BookOpen,
  Brain,
  Library,
  Bus,
  Settings,
  ClipboardList,
  Trophy,
  UserPlus,
  Megaphone,
  Building2,
  Calendar,
  Package,
  ReceiptIndianRupee,
  ClipboardCheck,
  Wrench,
  IdCard,
  ScrollText,
  BarChart3,
  FileText,
  HeartPulse,
  ShieldAlert,
  LifeBuoy,
  UtensilsCrossed,
  CalendarDays,
  Award,
  CalendarClock,
  Vote,
  Landmark,
  Crown,
  Target,
  Swords,
  Compass,
  Lightbulb,
  ArrowUpFromLine,
  UserCog,
  UsersRound,
  ShieldCheck,
  NotebookPen,
  MessageCircle,
  HandCoins,
} from "lucide-react";

// Single source of truth for the sidebar / settings module list.
// Kept in a plain JS module (not the layout component) so React Fast Refresh
// keeps working when consumers import this.
export const NAV = [
  { to: "/app", label: "Dashboard", icon: LayoutDashboard, end: true, roles: "*" },
  { to: "/app/admissions", label: "Admissions", icon: UserPlus, roles: ["admin", "principal"] },
  { to: "/app/students", label: "Students", icon: Users, roles: ["admin", "principal", "teacher", "accountant", "hr", "student", "parent"] },
  { to: "/app/teachers", label: "Teachers", icon: GraduationCap, roles: ["admin", "principal", "hr"] },
  { to: "/app/staff", label: "Staff Directory", icon: UsersRound, roles: ["admin", "principal", "hr", "accountant"] },
  { to: "/app/attendance", label: "Attendance", icon: CalendarCheck, roles: ["admin", "principal", "teacher", "parent", "student"] },
  { to: "/app/fees", label: "Fees & Finance", icon: Wallet, roles: ["admin", "principal", "accountant", "parent"] },
  { to: "/app/exams", label: "Exams & Results", icon: Trophy, roles: ["admin", "principal", "teacher", "student", "parent"] },
  { to: "/app/assignments", label: "Assignments", icon: NotebookPen, roles: ["admin", "principal", "teacher", "student", "parent"] },
  { to: "/app/timetable", label: "Timetable", icon: ClipboardList, roles: "*" },
  { to: "/app/library", label: "Library", icon: Library, roles: "*" },
  { to: "/app/transport", label: "Transport", icon: Bus, roles: ["admin", "principal", "parent", "student"] },
  { to: "/app/hostel", label: "Hostel", icon: Building2, roles: ["admin", "principal", "parent", "student"] },
  { to: "/app/payroll", label: "Payroll", icon: Briefcase, roles: ["admin", "principal", "accountant", "hr"] },
  { to: "/app/salary-advances", label: "Salary Advances", icon: HandCoins, roles: ["admin", "principal", "accountant", "hr"] },
  { to: "/app/learning", label: "Online Learning", icon: BookOpen, roles: "*" },
  { to: "/app/quizzes", label: "Quizzes", icon: Brain, roles: "*" },
  { to: "/app/events", label: "Events", icon: Calendar, roles: "*" },
  { to: "/app/inventory", label: "Inventory", icon: Package, roles: ["admin", "principal", "accountant"] },
  { to: "/app/expenses", label: "Expenses", icon: ReceiptIndianRupee, roles: ["admin", "principal", "accountant"] },
  { to: "/app/leave", label: "Leave", icon: ClipboardCheck, roles: "*" },
  { to: "/app/communications", label: "Communications", icon: Megaphone, roles: ["admin", "principal", "teacher", "hr"] },
  { to: "/app/messages", label: "Messages", icon: MessageCircle, roles: "*" },
  { to: "/app/maintenance", label: "Maintenance", icon: Wrench, roles: ["admin", "principal", "teacher"] },
  { to: "/app/visitors", label: "Visitors", icon: IdCard, roles: ["admin", "principal", "hr"] },
  { to: "/app/documents", label: "Documents", icon: FileText, roles: ["admin", "principal", "hr", "teacher", "parent", "student"] },
  { to: "/app/health", label: "Health", icon: HeartPulse, roles: ["admin", "principal", "teacher", "parent", "student"] },
  { to: "/app/discipline", label: "Discipline", icon: ShieldAlert, roles: ["admin", "principal", "teacher", "parent", "student"] },
  { to: "/app/safe-space", label: "Safe space", icon: LifeBuoy, roles: "*" },
  { to: "/app/achievements", label: "Achievements", icon: Trophy, roles: "*" },
  { to: "/app/cafeteria", label: "Cafeteria", icon: UtensilsCrossed, roles: "*" },
  { to: "/app/calendar", label: "Calendar", icon: CalendarDays, roles: "*" },
  { to: "/app/alumni", label: "Alumni", icon: Award, roles: ["admin", "principal", "hr", "teacher"] },
  { to: "/app/notices", label: "Notice Board", icon: Megaphone, roles: "*" },
  { to: "/app/ptm", label: "PTM Scheduling", icon: CalendarClock, roles: ["admin", "principal", "teacher", "parent", "hr"] },
  { to: "/app/polls", label: "Polls & Surveys", icon: Vote, roles: "*" },
  { to: "/app/scholarships", label: "Scholarships", icon: Landmark, roles: ["admin", "principal", "hr", "teacher", "parent"] },
  { to: "/app/house-points", label: "House Points", icon: Crown, roles: "*" },
  { to: "/app/fundraising", label: "Fundraising", icon: Target, roles: "*" },
  { to: "/app/sports", label: "Sports", icon: Swords, roles: "*" },
  { to: "/app/careers", label: "Careers", icon: Compass, roles: ["admin", "principal", "hr", "teacher", "parent", "student"] },
  { to: "/app/suggestions", label: "Suggestion Box", icon: Lightbulb, roles: "*" },
  { to: "/app/substitutes", label: "Substitutes", icon: UserCog, roles: ["admin", "principal", "hr", "teacher"] },
  { to: "/app/promotion", label: "Year-End Promotion", icon: ArrowUpFromLine, roles: ["admin", "principal"] },
  { to: "/app/reports", label: "Reports", icon: BarChart3, roles: ["admin", "principal", "accountant", "hr", "teacher"] },
  { to: "/app/access", label: "Users & Access", icon: ShieldCheck, roles: ["admin", "principal"] },
  { to: "/app/audit", label: "Audit Log", icon: ScrollText, roles: ["admin", "principal"] },
  { to: "/app/settings", label: "Settings", icon: Settings, roles: "*" },
];
